### ISSUE TITLE
二阶导

### ISSUE THREAD

**Issue by Huangdebo** [anzhi998/findpeaks#1]
你好：
        非常感谢你的开源代码。有一处不明白，为什么要加上 diff2 != 0 呢？

https://github.com/anzhi998/findpeaks/blob/8146a25e4da49f9a129cbfc35c01acc4d089c1df/findpeaks.h#L39

**Comment by anzhi998** [comment]
呃。。感谢您的仔细阅读，我看了一眼好像这里DIFF2这个变量没必要，甚至极端情况下会导致结果错误，应该是二阶导符号化后为-2就可以初步认定是备选点了，回忆了一下这可能是某个版本的代码遗留的没改，谢谢您指出问题。

**Comment by Huangdebo** [comment]
> 呃。。感谢您的仔细阅读，我看了一眼好像这里DIFF2这个变量没必要，甚至极端情况下会导致结果错误，应该是二阶导符号化后为-2就可以初步认定是备选点了，回忆了一下这可能是某个版本的代码遗留的没改，谢谢您指出问题。

感谢您的解答，谢谢！
